database:
  host: localhost
  user: CHANGETHIS
  password: CHANGETHIS
  database: CHANGETHIS
  tableprefix: secrets
  servername: CHANGETHIS
lobbyitem:
  #Give Player Secret Item by Join
  use: true
  #Lobby Item Slot (0-8)
  slot: 0
  worlds:
    - CHANGETHIS