#Plugin Language (en_EN, de_DE)
language: en_EN

#Database Login
database:
  host: localhost
  user: CHANGETHIS
  password: CHANGETHIS
  database: CHANGETHIS
  tableprefix: secrets

#Lobby-Item Settings
lobbyitem:
  #Give Player Secret Item by Join
  use: true
  #Lobby Item Slot (0-8)
  slot: 0
  #worlds where you have the lobby item
  worlds:
    - CHANGETHIS

#Reward Settings
rewards:
  #Runs a command as a console
  commandReward:
    enable: false
    command: give %player% diamond 1
  #Gives the player money via the Vault API
  economyReward:
    enable: false
    amount: 100.0

#Converter
convert: false